# Generated by Django 4.1.7 on 2023-03-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.IntegerField(max_length=50)),
                ('name_point', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=50, unique=True)),
                ('check_type', models.CharField(max_length=50)),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.point')),
            ],
        ),
    ]
